@echo off
echo Initializing git...
git init
echo Configuring user...
git config user.email "antigravity@example.com"
git config user.name "Antigravity"
echo Setting remote...
git remote remove origin
git remote add origin https://github.com/xhoneylemonx/New_backend.git
echo Adding files...
git add .
echo Committing...
git commit -m "Initial commit from Antigravity"
echo Pushing...
git branch -M main
git push -u origin main
echo Done.
